dist:
  - trusty

addons:
  apt:
    sources:
      - boost-latest
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
      - libpython2.7-dev

cache:
  apt: true
  directories:
    - lib
    - tools

language:
  - cpp

compiler:
  - g++

install:
  # Set the C++ compiler
  - sudo ln -sf /usr/bin/g++-6 /usr/bin/g++
  # Install CMake
  - ./travis/install_cmake.sh &> /dev/null
  # Install the dependencies
  - travis_wait 30 "./install_deps.sh &> /dev/null"

script:
  - ./build.sh